In [1]:
import pandas as pd
import re
from nltk.tokenize import word_tokenize

In [2]:
df = pd.read_csv('DATA_SET/final_test.csv')

In [3]:
df.head(-1)

                                                    text  label
0      The Face on Mars is nothing but a natural occu...      0
1      Students have a higher chance of catching a vi...      0
2      Driverless cars have good and bad things that ...      0
3      Some people might think that traveling in a gr...      1
4      How many of us students want to be forced to d...      0
...                                                  ...    ...
86581  Dear (Senator of Florida),\n\nIn my opinion I ...      0
86582  Dear Principal: I think we should have cell ph...      0
86583  Dear Teacher_NAME\n\nI think that if you try t...      0
86584  Venus is sometimes called the "meaning Star." ...      0
86585  The Seagoing Cowboy Bros\n\nDo you like going ...      0

[86586 rows x 2 columns]

In [4]:
print(df.isna().sum())

df = df.dropna()

text     0
label    0
dtype: int64

In [5]:
# Data Cleaning

def clean_text(text):
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    text = text.lower()

    words = word_tokenize(text)

    cleaned_text = ' '.join(words)
    cleaned_text = re.sub(r'\s+', ' ', cleaned_text).strip()
    return cleaned_text

df['cleaned_text'] = df['text'].apply(clean_text)

In [6]:
df.head(-1)

,text,label,cleaned_text
0,The Face on Mars is nothing but a natural occu...,0,the face on mars is nothing but a natural occu...
1,Students have a higher chance of catching a vi...,0,students have a higher chance of catching a vi...
2,Driverless cars have good and bad things that ...,0,driverless cars have good and bad things that ...
3,Some people might think that traveling in a gr...,1,some people might think that traveling in a gr...
4,How many of us students want to be forced to d...,0,how many of us students want to be forced to d...
...,...,...,...
86581,"Dear (Senator of Florida),\n\nIn my opinion I ...",0,dear senator of florida in my opinion i believ...
86582,Dear Principal: I think we should have cell ph...,0,dear principal i think we should have cell pho...
86583,Dear Teacher_NAME\n\nI think that if you try t...,0,dear teachername i think that if you try to st...
86584,"Venus is sometimes called the ""meaning Star."" ...",0,venus is sometimes called the meaning star its...
86585,The Seagoing Cowboy Bros\n\nDo you like going ...,0,the seagoing cowboy bros do you like going to ...

In [7]:
# Space remover for text

def space_remover(text):
    words = word_tokenize(text)
    text = ' '.join(words)
    return re.sub(r'\s+', ' ', text).strip()

df['text'] = df['text'].apply(space_remover)

In [8]:
df.head()

,text,label,cleaned_text
0,The Face on Mars is nothing but a natural occu...,0,the face on mars is nothing but a natural occu...
1,Students have a higher chance of catching a vi...,0,students have a higher chance of catching a vi...
2,Driverless cars have good and bad things that ...,0,driverless cars have good and bad things that ...
3,Some people might think that traveling in a gr...,1,some people might think that traveling in a gr...
4,How many of us students want to be forced to d...,0,how many of us students want to be forced to d...

In [18]:
df.to_csv('DATA_SET/final_test_v2.csv', index=False)